#' @name pre_rank
#' @title pre_rank: pre-ranked miRNA expression data
#'
#' @description This dataset contains miRNA expression values across multiple tissue samples.
#' The miRNAs included represent canonical variants (referred to as "canon" in the `Variant` column).
#'
#' @format A data frame with X rows and Y variables:
#' \describe{
#'   \item{id}{Unique identifier for each miRNA sequence (character).}
#'   \item{mir_names}{Collapsed miRNA names corresponding to each `id` (character).}
#'   \item{Read}{The sequence read corresponding to the miRNA (character).}
#'   \item{tissue_sample}{Name of the tissue and sample (character).}
#'   \item{rpm}{Expression value (Reads Per Million) for the miRNA in the corresponding tissue sample (numeric).}
#'   \item{source}{Source of the sample (factor).}
#'   \item{tissue}{Specific tissue from which the sample was taken (factor).}
#'   \item{sample}{Unique identifier for the specific tissue sample (factor).}
#'   \item{new_lab}{Label for the tissue used in analysis (factor).}
#'   \item{breed}{Breed of the horse from which the tissue sample was obtained (factor).}
#'   \item{sex}{Sex of the horse (factor).}
#' }
#'
#' @details
#' This dataset was generated by filtering and organizing miRNA data to retain only canonical variants, 
#' replacing missing values in the `Variant` column with "canon". The dataset was then transformed to a 
#' long format to facilitate analysis across different tissue samples. 
#'
#' The `tissue_sample` column was used to join this data with additional metadata, providing contextual 
#' information such as the tissue source, tissue type, and sample details.
#'
#' @source 
#' The data was originally sourced from the `isomir_rpm.isomirmap_exp_filt.tsv` file. The miRNA expression 
#' values were normalized as Reads Per Million (RPM) to allow for comparison across samples.
#'
#' @examples
#' # Loading the dataset
#' data(pre_rank)
#'
#' # Summarizing the dataset
#' summary(pre_rank)
#'
"pre_rank"

